[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "iamstevesplash", email = "stevesplash4@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "aiortc>=1.14.0",
    "cryptography>=49.0.0",
    "httpx>=0.28.1",
    "shared",
    "websockets>=16.0",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
shared = { workspace = true }

[tool.uv.build-backend]
module-name = "src"
module-root = ""
